function ssxy_te_gradx = spgr_gradx_cmplx_gen(M0,T1,T2,kap,dw,R2p,flip,TR,TE)
%SPGR_GRADX_CMPLX_GEN
%    SSXY_TE_GRADX = SPGR_GRADX_CMPLX_GEN(M0,T1,T2,KAP,DW,R2P,FLIP,TR,TE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Jan-2018 10:23:59

t2 = flip.*kap;
t3 = 1.0./T1;
t10 = TR.*t3;
t4 = exp(-t10);
t5 = TE.*dw.*1i;
t6 = exp(t5);
t7 = 1.0./T2;
t8 = R2p+t7;
t17 = TE.*t8;
t9 = exp(-t17);
t11 = sin(t2);
t12 = cos(t2);
t13 = t4.*t12;
t14 = t13-1.0;
t15 = 1.0./t14;
t16 = 1.0./T1.^2;
t18 = t4-1.0;
ssxy_te_gradx = [t6.*t9.*t11.*t15.*t18.*1i,M0.*TR.*t4.*t6.*t9.*t11.*t15.*t16.*1i-M0.*TR.*t4.*t6.*t9.*t11.*t12.*1.0./t14.^2.*t16.*t18.*1i,M0.*1.0./T2.^2.*TE.*t6.*t9.*t11.*t15.*t18.*1i];
