function mag_ssxy_te_hessx = spgr_hessx_abs_gen(M0,T1,T2,kap,R2p,flip,TR,TE)
%SPGR_HESSX_ABS_GEN
%    MAG_SSXY_TE_HESSX = SPGR_HESSX_ABS_GEN(M0,T1,T2,KAP,R2P,FLIP,TR,TE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Jan-2018 10:24:05
n = length(M0);
t0 = zeros(n,1);

t2 = 1.0./T1;
t11 = TR.*t2;
t3 = exp(-t11);
t4 = flip.*kap;
t5 = 1.0./T1.^2;
t6 = sin(t4);
t7 = abs(t6);
t8 = 1.0./T2;
t9 = R2p+t8;
t15 = TE.*t9;
t10 = exp(-t15);
t12 = cos(t4);
t13 = t3.*t12;
t14 = t13-1.0;
t16 = 1.0./t14;
t17 = t3-1.0;
t18 = TR.*t3.*t5.*t7.*t10.*t16;
t19 = 1.0./t14.^2;
t20 = t18-TR.*t3.*t5.*t7.*t10.*t12.*t17.*t19;
t21 = T1.*TE;
t22 = R2p.*T1.*T2.*TE;
t23 = t12.^2;
t24 = exp(t11);
t25 = 1.0./T2.^2;
t26 = TE.*t7.*t10.*t16.*t17.*t25;
t27 = M0.*TE.*TR.*t3.*t5.*t7.*t10.*t16.*t25;
t28 = t27-M0.*TE.*TR.*t3.*t5.*t7.*t10.*t12.*t17.*t19.*t25;
% mag_ssxy_te_hessx = reshape([0.0,t20,t26,t20,(M0.*1.0./T1.^4.*TR.*t7.*t24.*(t12-1.0).*(T1.*t12.*2.0-T1.*t24.*2.0+TR.*t12+TR.*t24))./(exp(t2.*t8.*(t21+t22+T2.*TR.*3.0))-t12.*exp(t2.*t8.*(t21+t22+T2.*TR.*2.0)).*3.0+t23.*exp(t2.*t8.*(t21+t22+T2.*TR)).*3.0-t12.*t23.*exp(TE.*t8.*(R2p.*T2+1.0))),t28,t26,t28,M0.*1.0./T2.^3.*TE.*t7.*t10.*t16.*t17.*-2.0+M0.*1.0./T2.^4.*TE.^2.*t7.*t10.*t16.*t17],[1,3,3]);
mag_ssxy_te_hessx = reshape([t0,t20,t26,t20,(M0.*1.0./T1.^4.*TR.*t7.*t24.*(t12-1.0).*(T1.*t12.*2.0-T1.*t24.*2.0+TR.*t12+TR.*t24))./(exp(t2.*t8.*(t21+t22+T2.*TR.*3.0))-t12.*exp(t2.*t8.*(t21+t22+T2.*TR.*2.0)).*3.0+t23.*exp(t2.*t8.*(t21+t22+T2.*TR)).*3.0-t12.*t23.*exp(TE.*t8.*(R2p.*T2+1.0))),t28,t26,t28,M0.*1.0./T2.^3.*TE.*t7.*t10.*t16.*t17.*-2.0+M0.*1.0./T2.^4.*TE.^2.*t7.*t10.*t16.*t17],[n,3,3]);
