function ssxy_te_hessx = spgr_hessx_cmplx_gen(M0,T1,T2,kap,dw,R2p,flip,TR,TE)
%SPGR_HESSX_CMPLX_GEN
%    SSXY_TE_HESSX = SPGR_HESSX_CMPLX_GEN(M0,T1,T2,KAP,DW,R2P,FLIP,TR,TE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Jan-2018 10:24:03
n = length(M0);
t0 = zeros(n,1);

t2 = 1.0./T1;
t11 = TR.*t2;
t3 = exp(-t11);
t4 = flip.*kap;
t5 = 1.0./T1.^2;
t6 = TE.*dw.*1i;
t7 = exp(t6);
t8 = 1.0./T2;
t9 = R2p+t8;
t16 = TE.*t9;
t10 = exp(-t16);
t12 = cos(t4);
t13 = sin(t4);
t14 = t3.*t12;
t15 = t14-1.0;
t17 = 1.0./t15;
t18 = t3-1.0;
t19 = TR.*t3.*t5.*t7.*t10.*t13.*t17.*1i;
t20 = 1.0./t15.^2;
t21 = TR.*t3.*t5.*t7.*t10.*t12.*t13.*t18.*t20.*-1i;
t22 = t19+t21;
t23 = T1.*TE;
t24 = R2p.*T1.*T2.*TE;
t25 = t12.^2;
t26 = TR.*2.0;
t27 = T1.*TE.*dw.*1i;
t28 = t26+t27;
t29 = t2.*t28;
t30 = exp(t29);
t31 = TR+t27;
t32 = t2.*t31;
t33 = exp(t32);
t34 = 1.0./T2.^2;
t35 = TE.*t7.*t10.*t13.*t17.*t18.*t34.*1i;
t36 = M0.*TE.*TR.*t3.*t5.*t7.*t10.*t13.*t17.*t34.*1i;
t37 = M0.*TE.*TR.*t3.*t5.*t7.*t10.*t12.*t13.*t18.*t20.*t34.*-1i;
t38 = t36+t37;
t39 = exp(t11);
% ssxy_te_hessx = reshape([0.0,t22,t35,t22,(M0.*1.0./T1.^4.*TR.*t13.*(t12-1.0).*(T1.*t30.*-2.0i+TR.*t30.*1i+T1.*t12.*t33.*2.0i+TR.*t12.*t33.*1i))./(exp(t2.*t8.*(t23+t24+T2.*TR.*3.0))-t12.*exp(t2.*t8.*(t23+t24+T2.*TR.*2.0)).*3.0+t25.*exp(t2.*t8.*(t23+t24+T2.*TR)).*3.0-t12.*t25.*exp(TE.*t8.*(R2p.*T2+1.0))),t38,t35,t38,(M0.*1.0./T2.^4.*TE.*t13.*exp(t6-t16).*(T2.*2.0-TE).*(t39-1.0).*1i)./(t12-t39)],[1,3,3]);
ssxy_te_hessx = reshape([t0,t22,t35,t22,(M0.*1.0./T1.^4.*TR.*t13.*(t12-1.0).*(T1.*t30.*-2.0i+TR.*t30.*1i+T1.*t12.*t33.*2.0i+TR.*t12.*t33.*1i))./(exp(t2.*t8.*(t23+t24+T2.*TR.*3.0))-t12.*exp(t2.*t8.*(t23+t24+T2.*TR.*2.0)).*3.0+t25.*exp(t2.*t8.*(t23+t24+T2.*TR)).*3.0-t12.*t25.*exp(TE.*t8.*(R2p.*T2+1.0))),t38,t35,t38,(M0.*1.0./T2.^4.*TE.*t13.*exp(t6-t16).*(T2.*2.0-TE).*(t39-1.0).*1i)./(t12-t39)],[n,3,3]);
