function mag_ssxy_te_gradx = spgr_gradx_abs_gen(M0,T1,T2,kap,R2p,flip,TR,TE)
%SPGR_GRADX_ABS_GEN
%    MAG_SSXY_TE_GRADX = SPGR_GRADX_ABS_GEN(M0,T1,T2,KAP,R2P,FLIP,TR,TE)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Jan-2018 10:24:00

t2 = flip.*kap;
t3 = 1.0./T1;
t10 = TR.*t3;
t4 = exp(-t10);
t5 = sin(t2);
t6 = abs(t5);
t7 = 1.0./T2;
t8 = R2p+t7;
t16 = TE.*t8;
t9 = exp(-t16);
t11 = cos(t2);
t12 = t4.*t11;
t13 = t12-1.0;
t14 = 1.0./t13;
t15 = 1.0./T1.^2;
t17 = t4-1.0;
mag_ssxy_te_gradx = [t6.*t9.*t14.*t17,M0.*TR.*t4.*t6.*t9.*t14.*t15-M0.*TR.*t4.*t6.*t9.*t11.*1.0./t13.^2.*t15.*t17,M0.*1.0./T2.^2.*TE.*t6.*t9.*t14.*t17];
