function sTE_xy = SE_shortTR_gen(M0,T1,T2,kap,TR,TE,flip_ex,flip_ref,dw)
%SE_SHORTTR_GEN
%    STE_XY = SE_SHORTTR_GEN(M0,T1,T2,KAP,TR,TE,FLIP_EX,FLIP_REF,DW)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-May-2016 08:38:07

t2 = 1.0./T1;
t5 = TE.*t2.*(1.0./2.0);
t3 = exp(-t5);
t4 = 1.0./T2;
t6 = TE.*t4.*(1.0./2.0);
t7 = exp(t6);
t8 = flip_ex.*kap;
t9 = cos(t8);
t10 = flip_ref.*kap;
t11 = exp(t5);
t17 = TR.*2.0;
t12 = TE-t17;
t13 = t2.*t12.*(1.0./2.0);
t14 = exp(t13);
t15 = TE.*dw.*(1.0./2.0);
t16 = sin(t10);
t18 = cos(t10);
t19 = sin(t15);
t20 = sin(t8);
t21 = t7.*t11;
t22 = t11.*t14.*t16.*t19.*t20;
t30 = t7.*t9.*t14.*t18;
t23 = t21+t22-t30;
t24 = 1.0./t23;
t25 = t11.*t14.*t18;
t31 = t11.*t14;
t32 = t14.*t18;
t26 = t11+t25-t31-t32;
t27 = exp(-t6);
t28 = t3-1.0;
t29 = M0.*t28;
t33 = t29-M0.*t3.*t7.*t9.*t24.*t26;
t34 = t16.*t33;
t35 = t34-M0.*t18.*t19.*t20.*t24.*t26;
t36 = cos(t15);
sTE_xy = t19.*t27.*t35.*1i-t27.*t35.*t36+M0.*t20.*t24.*t26.*t27.*t36.^2.*1i+M0.*t19.*t20.*t24.*t26.*t27.*t36;
