  function [fval] = f(x, nu, P, dim, bool)
%|function [fval] = f(x, nu, P, dim, bool)
%|
%|  signal model function evaluation
%|
%|  inputs
%|    x         {L cell}        latent object parameters with cells size [V]
%|    nu        {N cell}        known parameters with cells size [Vloc]
%|    P         [1x1 struct]    scan parameters
%|                                1st field: data type (ir,se,sp,de)
%|                                2nd field: scan parameter, as appropriate
%|     .*.tr    [S.*]               repetition times                                          ms
%|     .*.ti    [S.ir]              inversion times                                           ms
%|     .*.te    [S.* E.*]           echo times                                                ms
%|     .*.ainv  [S.ir]              nominal effective flip angle of inversion                 rad
%|     .*.aex   [S.*]               nominal flip angle of excitation                          rad
%|     .*.aref  [S.*]               nominal flip angle of refocusing                          rad
%|    dim       [1x1 struct]    object containing dimension info  
%|    bool      [1x1 struct]    boolean variables               
%|     .mag.*   false|true        using magnitude (ir,se,sp,de) data     
%|
%|  outputs
%|    fval      [DV]            signal model function evaluations
%|
%|  version control
%|    1.1       2016-06-02      original
%|    1.2       2016-06-06      added magnitude signal options
%|    1.3       2016-06-08      compatibility with spgr/dess
%|    1.4       2016-06-27      new se-ir signal model
%|    1.5       2016-06-28      nu now expected as cell (previously struct)

% initialize with matrix format for convenient indexing
dim.Vloc = numel(x{1});                                                 % [D Vloc]
fval = NaN(dim.D, dim.Vloc);
row = 1;

% se-ir function calls
for s = 1:dim.S.ir
  fval(row,:) = IR_fun_v4(...
    x{1:3},...
    P.ir.tr(s), P.ir.ti(s), P.ir.te(s,1),...
    'inveff', x{4},...
    'kap', nu{1},...
    'wf', nu{2},...
    'flip_inv', P.ir.ainv(s),...
    'flip_ex', P.ir.aex(s),...
    'flip_ref', P.ir.aref(s),...
    'mag', bool.mag.ir);
  row = row+1;
end

% se function calls
for s = 1:dim.S.se
  fval(row,:) = SE_fun_v4(...
    x{1:3},...
    P.se.tr(s), P.se.te(s,1),...
    'kap', nu{1},...
    'wf', nu{2},...
    'flip_ex', P.se.aex(s),...
    'flip_ref', P.se.aref(s),...
    'mag', bool.mag.se);
  row = row+1;
end

% spgr function calls
for s = 1:dim.S.sp
  fval(row,:) = spgr_fun_v2(...
    x{1:3},...
    P.sp.aex(s), P.sp.tr(s), P.sp.te(s,1),...
    'kap', nu{1},...
    'dw', nu{2},...
    'R2p', nu{3},...
    'mag', bool.mag.sp);
  row = row+1;
end

% dess function calls
for s = 1:dim.S.de
  [fval(row,:), fval(row+dim.S.de,:)] = dess_fun_v2(...
    x{1:3},...
    P.de.aex(s), P.de.tr(s), P.de.te(s,1), P.de.te(s,2),...
    'kap', nu{1},...
    'dw', nu{2},...
    'R2p', nu{3},...
    'mag', bool.mag.de);
  row = row+1;
end

% reshape for output
fval = col(fval);                                                       % [DVloc]
end