function mag_smxy_tem_gradx = dess_echo2_gradx_abs_gen(M0,T1,T2,kap,R2p,flip,TR,TEm)
%DESS_ECHO2_GRADX_ABS_GEN
%    MAG_SMXY_TEM_GRADX = DESS_ECHO2_GRADX_ABS_GEN(M0,T1,T2,KAP,R2P,FLIP,TR,TEM)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Jan-2018 11:49:12

t2 = 1.0./T2;
t12 = TR.*t2.*2.0;
t3 = exp(-t12);
t5 = 1.0./T1;
t6 = TR.*t5;
t7 = exp(-t6);
t8 = flip.*kap;
t9 = cos(t8);
t4 = -t7+t9;
t10 = flip.*kap.*(1.0./2.0);
t11 = tan(t10);
t13 = t4.^2;
t14 = t7.*t9;
t15 = t14-1.0;
t16 = 1.0./t15.^2;
t17 = t3.*t13.*t16;
t18 = t17-1.0;
t19 = 1.0./t18;
t20 = exp(t6);
t21 = -t3+1.0;
t22 = sqrt(t21);
t23 = R2p-t2;
t31 = TEm.*t23;
t24 = exp(-t31);
t25 = t3-1.0;
t26 = t19.*t25;
t27 = sqrt(t26);
t28 = t27-1.0;
t29 = t11.*t28;
t30 = abs(t29);
t32 = 1.0./T2.^2;
t33 = 1.0./t18.^2;
mag_smxy_tem_gradx = [t24.*t30,-M0.*1.0./T1.^2.*TR.*t11.*1.0./sqrt(-t19).*t22.*t33.*exp(-TR.*t2.*t5.*(T1.*2.0-T2)).*exp(-TEm.*t2.*(R2p.*T2-1.0)).*sign(t11.*(sqrt(-t19).*t22-1.0)).*(t9.^2-1.0).*1.0./(t9-t20).^3.*(t9.*t20-1.0),-M0.*TEm.*t24.*t30.*t32+M0.*t11.*t24.*1.0./sqrt(t26).*sign(t29).*(TR.*t3.*t19.*t32.*2.0-TR.*t3.*t13.*t16.*t25.*t32.*t33.*2.0).*(1.0./2.0)];
