function sTI_TE_xy = IR_shortTR_gen(M0,T1,T2,kap,TR,TI,TE,flip_ex,flip_ref,dw)
%IR_SHORTTR_GEN
%    STI_TE_XY = IR_SHORTTR_GEN(M0,T1,T2,KAP,TR,TI,TE,FLIP_EX,FLIP_REF,DW)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    27-May-2016 22:47:58

t2 = 1.0./T1;
t5 = TE.*t2.*(1.0./2.0);
t3 = exp(-t5);
t7 = TI.*t2;
t4 = exp(-t7);
t6 = 1.0./T2;
t8 = TE.*t6.*(1.0./2.0);
t9 = exp(t8);
t10 = flip_ex.*kap;
t11 = cos(t10);
t12 = flip_ref.*kap;
t13 = TI.*2.0;
t22 = TR.*2.0;
t14 = TE+t13-t22;
t15 = t2.*t14.*(1.0./2.0);
t16 = exp(t15);
t17 = exp(t5);
t18 = TE.*dw.*(1.0./2.0);
t19 = sin(t12);
t20 = exp(t7);
t21 = t9.*t17.*t20;
t23 = cos(t12);
t24 = t9.*t11.*t16.*t23;
t25 = sin(t18);
t26 = sin(t10);
t27 = t4-1.0;
t28 = M0.*t27;
t29 = t16.*t17.*t19.*t25.*t26;
t30 = t9.*t11.*t16.*t20.*t23;
t31 = t9.*t16.*t17.*t20.*t23;
t40 = t9.*t16.*t20.*t23;
t41 = t9.*t16.*t17.*t20;
t42 = t16.*t17.*t19.*t20.*t25.*t26;
t32 = t21-t24+t29+t30+t31-t40-t41-t42;
t33 = exp(-t8);
t34 = t21+t24-t29;
t35 = 1.0./t34;
t36 = M0.*t4.*t32.*t35;
t37 = t28+t36;
t38 = t3-1.0;
t39 = M0.*t38;
t43 = t3.*t11.*t37;
t44 = t39+t43;
t45 = t19.*t44;
t46 = t23.*t25.*t26.*t33.*t37;
t47 = t45+t46;
t48 = cos(t18);
t49 = exp(-TE.*t6);
sTI_TE_xy = t25.*t33.*t47.*1i-t33.*t47.*t48-t26.*t37.*t48.^2.*t49.*1i-t25.*t26.*t37.*t48.*t49;
